# Generated by Django 6.0.2 on 2026-02-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_etl_processed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='report_type',
            field=models.CharField(choices=[('hourly_sales', 'Hourly Sales'), ('daily_sales', 'Daily Sales'), ('product_sales', 'Product Sales'), ('payments_report', 'Payments Report / تقرير المقبوضات')], max_length=32),
        ),
    ]
