# Generated by Django 6.0.2 on 2026-02-23 02:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0013_journalentry_branch_alter_journalentry_source_type'),
        ('org', '0023_organization_alter_adminnotification_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AS1001', max_length=16)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('equipment', 'معدات'), ('vehicle', 'سيارة'), ('furniture', 'أثاث'), ('machinery', 'آليات (ماكينات قهوة، إلخ)'), ('other', 'أخرى')], db_index=True, max_length=24)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='القيمة المتبقية عند نهاية العمر الافتراضي', max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField(default=60, help_text='العمر الافتراضي بالأشهر (مثلاً 60 = 5 سنوات)')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'الخط المستقيم')], default='straight_line', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='org.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='org.brand')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AS1002', max_length=16)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciations', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_depreciations', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='القيد المحاسبي للإهلاك', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciations', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Asset Depreciation',
                'verbose_name_plural': 'Asset Depreciations',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('asset', 'period_month', 'period_year')},
            },
        ),
    ]
