# Generated by Django 6.0.2 on 2026-02-23 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0015_add_stock_transfer_uuid'),
        ('org', '0025_moduleconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralKitchenBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='central_kitchen', to='org.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='CK1002', max_length=16)),
                ('indent_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'معتمد'), ('delivered', 'تم التسليم')], db_index=True, default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_indents', to='org.brand')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents_out', to='org.branch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_indents', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents_in', to='org.branch')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='CK1003', max_length=16)),
                ('note_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_notes', to=settings.AUTH_USER_MODEL)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='central_kitchen.internalindent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InternalIndentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='central_kitchen.internalindent')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indent_lines', to='inventory.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indent_line_units', to='inventory.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='CK1001', max_length=16)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('released', 'صادر'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], db_index=True, default='draft', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to=settings.AUTH_USER_MODEL)),
                ('kitchen_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='org.branch')),
                ('product', models.ForeignKey(help_text='المنتج الوسيط المُنتَج', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.foodicsproduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.unit')),
            ],
            options={
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='inventory.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='central_kitchen.productionorder')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_line_units', to='inventory.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
