# Generated by Django 6.0.2 on 2026-02-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تكلفة الإنتاج المحسوبة من المواد الخام', max_digits=14, null=True),
        ),
    ]
