# Generated by Django 6.0.2 on 2026-02-23 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم وصفي للقاعدة', max_length=128)),
                ('rule_type', models.CharField(choices=[('shift_not_opened_within_minutes', 'تنبيه: وردية لم تُفتح في موعدها (بعد X دقيقة)'), ('shift_not_closed_by_deadline', 'تنبيه: وردية لم تُقفل في موعدها'), ('low_stock_alert', 'تنبيه: مخزون منخفض'), ('variance_threshold', 'تنبيه: فرق نقدي يتجاوز حداً معيناً')], db_index=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(default=list)),
                ('recipient_type', models.CharField(choices=[('owner', 'المالك (SAIF)'), ('branch_supervisor', 'مشرف الفرع'), ('brand_manager', 'مدير العلامة'), ('custom_users', 'مستخدمون محددون')], default='owner', max_length=32)),
                ('recipient_user_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32)),
                ('recipient_id', models.IntegerField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('reference', models.CharField(db_index=True, help_text='لتجنب إعادة الإرسال', max_length=256)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationrule')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['reference'], name='notificatio_referen_c7673f_idx')],
            },
        ),
    ]
