"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

# [SAFETY LOCK] ZeroTier/LAN – 10.219.168.113 is current ZeroTier IP for Foodics sync
ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '172.23.135.143', '10.219.168.113']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'django_otp',
    'django_otp.plugins.otp_totp',
    # Local apps
    'core',
    'org',
    'shifts',
    'inventory',
    'imports',
    'analytics',
    'foodics',
    'accounting',
    'financials',
    'procurement',
    'hr',
    'assets',
    'pos',
    'crm',
    'central_kitchen',
    'quality',
    'bi',
    'currencies',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'core.tenant_middleware.RequestContextMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database: Env-driven switch for local vs Render deployment
# - Local (no DATABASE_URL): SQLite db.sqlite3
# - Render: PostgreSQL via DATABASE_URL (Render injects from connected Postgres)
# - Render free Postgres has 90-day limit; migrate to paid or external DB later if needed
# - Set USE_SQLITE=1 to force SQLite even when DATABASE_URL exists (local dev)
DATABASES = {}
_use_sqlite = os.getenv('USE_SQLITE', '').lower() in ('1', 'true', 'yes')
_database_url = os.getenv('DATABASE_URL')
_has_postgres = _database_url and dj_database_url

if _use_sqlite or not _has_postgres:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
else:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# Disabled to allow weak passwords (e.g. '123') for local/dev admin users.

AUTH_PASSWORD_VALIDATORS = []
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'Asia/Riyadh')

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images) - served by WhiteNoise in production
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Excel uploads, accounting settlements) - local storage
# Render ephemeral disk: uploads lost on redeploy; consider S3 for persistence
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# [SAFETY LOCK] CORS – ZeroTier 10.219.168.113 for network/Foodics access
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://172.23.135.143:5173",
    "http://172.23.135.143:8000",
    "http://10.219.168.113:5173",
    "http://10.219.168.113:8000",
]
CORS_ALLOW_CREDENTIALS = True

# [SAFETY LOCK] CSRF – 10.219.168.113 ZeroTier + legacy IPs for network access
def _get_csrf_origins():
    origins = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://172.23.135.143:5173",
        "http://172.23.135.143:8000",
        "http://10.219.168.113:5173",
        "http://10.219.168.113:8000",
        "http://192.168.1.35:5173",
        "http://192.168.1.35:8000",
    ]
    try:
        import socket
        host_ip = socket.gethostbyname(socket.gethostname())
        if host_ip and host_ip not in ("127.0.0.1", "127.0.0.0"):
            for port in (5173, 8000):
                origins.append(f"http://{host_ip}:{port}")
    except Exception:
        pass
    seen = set()
    return [o for o in origins if o not in seen and not seen.add(o)]

CSRF_TRUSTED_ORIGINS = _get_csrf_origins()

# Long-lived sessions for branch devices (30 days)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Open API - للتكامل مع بوابات الدفع، التوصيل، الضرائب، تطبيقات الموبايل
SPECTACULAR_SETTINGS = {
    'TITLE': 'Smart Operations Hub API',
    'DESCRIPTION': (
        'Enterprise ERP API - التوثيق التلقائي لجميع الـ APIs. '
        'جاهز للربط مع أنظمة خارجية، بوابات الدفع، التوصيل، الضرائب، وتطبيقات الموبايل.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'auth', 'description': 'تسجيل الدخول والمستخدم الحالي'},
        {'name': 'org', 'description': 'المنظمة، الفروع، العلامات، المستخدمون، الأدوار والصلاحيات'},
        {'name': 'shifts', 'description': 'الورديات وإقفال الشفتات'},
        {'name': 'inventory', 'description': 'المخزون، المنتجات، التكاليف والربح'},
        {'name': 'financials', 'description': 'الملخص المالي والتقارير'},
        {'name': 'notifications', 'description': 'محرك التنبيهات وقواعد الإرسال'},
    ],
}

# [Optional] Override Net Sales (صافي المبيعات) when env set - for verified report correction.
# Set NET_SALES_OVERRIDE=981459 to force display. Remove when Foodics sync is correct.
NET_SALES_OVERRIDE = None
_raw = os.getenv("NET_SALES_OVERRIDE", "").strip()
if _raw and _raw.replace(",", "").replace(".", "").isdigit():
    try:
        NET_SALES_OVERRIDE = float(_raw.replace(",", ""))
    except ValueError:
        pass
