# Generated by Django 6.0.2 on 2026-02-23 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0025_moduleconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_checklists', to='org.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.auditchecklist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BranchVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_visits', to='org.branch')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='quality.auditchecklist')),
                ('visited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='BranchVisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quality/visits/')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_results', to='quality.auditchecklistitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.branchvisit')),
            ],
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_type', models.CharField(default='temperature', max_length=24)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('min_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iot_devices', to='org.branch')),
            ],
            options={
                'ordering': ['branch', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='IoTAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, default='critical', max_length=16)),
                ('message', models.CharField(max_length=500)),
                ('value_recorded', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='quality.iotdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='celsius', max_length=16)),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='quality.iotdevice')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
    ]
