# Generated by Django 6.0.2 on 2026-02-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_hr_geo_payroll_ext'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=2, help_text='0-100', max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_scores', to='org.branch')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('branch', 'period_month', 'period_year')},
            },
        ),
    ]
