# Generated by Django 6.0.2 on 2026-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_system_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyaccountingstatus',
            name='system_code',
            field=models.CharField(db_index=True, default='AC1003', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='foodicspaymentrecord',
            name='system_code',
            field=models.CharField(db_index=True, default='AC1002', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='foodicssettlement',
            name='system_code',
            field=models.CharField(db_index=True, default='AC1001', help_text='ERP hierarchy code', max_length=16),
        ),
    ]
