# Generated by Django 6.0.2 on 2026-02-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_dailyaccountingstatus_system_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AC1004', max_length=16)),
                ('code', models.CharField(db_index=True, help_text='رقم الحساب مثل 01, 01101', max_length=32, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='المستوى 1-5')),
                ('account_type', models.CharField(choices=[('رئيسي', 'رئيسي'), ('تحليلي', 'تحليلي')], default='تحليلي', max_length=24)),
                ('statement', models.CharField(choices=[('المركز المالي', 'المركز المالي'), ('قائمة الدخل', 'قائمة الدخل')], default='المركز المالي', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartaccount')),
            ],
            options={
                'verbose_name': 'Chart Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
    ]
