# Generated by Django 6.0.2 on 2026-02-17 08:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_chart_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='رصيد الحساب – يُحدَّث من رفع الإكسل أو القيود', max_digits=18),
        ),
    ]
