# Generated by Django 6.0.2 on 2026-02-18 22:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_add_chart_account_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AC1005', max_length=16)),
                ('source_file', models.CharField(help_text='اسم ملف الإكسل المصدر', max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Upload',
                'verbose_name_plural': 'Cost Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AC1005', max_length=16)),
                ('account_code', models.CharField(db_index=True, max_length=32)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', help_text='الوصف من ملف الإكسل', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source_file', models.CharField(blank=True, default='', help_text='اسم ملف الإكسل المصدر', max_length=255)),
                ('is_excluded', models.BooleanField(default=False, help_text='استبعاد من الحساب (رقم وهمي – آيبان، هاتف، إلخ)')),
                ('upload', models.ForeignKey(blank=True, help_text='رفع الإكسل الذي جاء منه هذا السطر', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.costupload')),
            ],
            options={
                'verbose_name': 'Cost Audit Entry',
                'verbose_name_plural': 'Cost Audit Entries',
                'ordering': ['-amount', '-created_at'],
                'indexes': [models.Index(fields=['account_code', 'is_excluded'], name='accounting__account_a707c9_idx')],
            },
        ),
    ]
