# Generated by Django 6.0.2 on 2026-02-18 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_cost_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='AC1006', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('entry_type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], db_index=True, max_length=8)),
                ('reason', models.TextField(help_text='سبب التسوية')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_adjustments', to='accounting.chartaccount')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Adjustment',
                'verbose_name_plural': 'Manual Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
