# Generated by Django 6.0.2 on 2026-02-23 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_add_in_transit_chart_account'),
        ('shifts', '0006_add_closing_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('shift_closing__isnull', False)), fields=('shift_closing',), name='unique_journal_per_shift_closing'),
        ),
    ]
