# Generated by Django 6.0.2 on 2026-02-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_unique_journal_per_shift_closing'),
        ('org', '0023_organization_alter_adminnotification_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع – للتقارير الموحدة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='org.branch'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('shift_closing', 'إقفال وردية'), ('manual', 'يدوي'), ('goods_receipt', 'استلام بضاعة'), ('supplier_invoice', 'فاتورة مورد'), ('payroll', 'رواتب'), ('depreciation', 'إهلاك أصول')], db_index=True, max_length=24),
        ),
    ]
