# Generated by Django 6.0.2 on 2026-02-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_journalentry_branch_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('shift_closing', 'إقفال وردية'), ('manual', 'يدوي'), ('goods_receipt', 'استلام بضاعة'), ('supplier_invoice', 'فاتورة مورد'), ('payroll', 'رواتب'), ('depreciation', 'إهلاك أصول'), ('pos_sale', 'بيع نقاط البيع')], db_index=True, max_length=24),
        ),
    ]
