# Generated by Django 6.0.2 on 2026-03-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_journalentry_source_type'),
        ('hr', '0003_hr_geo_payroll_ext'),
        ('org', '0032_add_kds_order_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع – ربط المصروف/الإيراد بموقع', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='org.branch'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='العلامة – أداء حسب العلامة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='org.brand'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='مركز التكلفة / القسم', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='hr.costcenter'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='موظف – مصروفات أو عمولات حسب الموظف', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='معرف المستند (رقم فاتورة، رقم استلام، إلخ)', max_length=64),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reference_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='نوع المستند المرتبط، مثل: invoice, grn, transfer', max_length=32),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['branch', 'journal_entry'], name='jel_branch_je_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['brand', 'journal_entry'], name='jel_brand_je_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['cost_center', 'journal_entry'], name='jel_cc_je_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['employee', 'journal_entry'], name='jel_emp_je_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['reference_type', 'reference_id'], name='jel_ref_type_id_idx'),
        ),
    ]
