# Generated by Django 6.0.2 on 2026-02-23 02:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0014_alter_journalentry_source_type'),
        ('org', '0024_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('price_add', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('modifiers', models.ManyToManyField(blank=True, related_name='groups', to='pos.productmodifier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('items', models.JSONField(default=list, help_text='[{product_sku, product_name, qty, unit_price, modifiers, discount_amount}]')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة / شبكة'), ('delivery_app', 'تطبيق توصيل')], db_index=True, default='cash', max_length=24)),
                ('status', models.CharField(choices=[('completed', 'مكتملة'), ('pending_sync', 'انتظار المزامنة (Offline)')], db_index=True, default='completed', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='org.branch')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
