# Generated by Django 6.0.2 on 2026-02-23 02:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0015_add_stock_transfer_uuid'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifier',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='للخصم من المخزون عند الاختيار', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_modifiers', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='productmodifier',
            name='modifier_type',
            field=models.CharField(db_index=True, default='addon', max_length=24),
        ),
        migrations.AddField(
            model_name='productmodifier',
            name='qty_per_use',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='كمية المكوّن المُخصمة لكل استخدام (بالوحدة الأساسية)', max_digits=10),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='terminal_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة / شبكة'), ('wallet', 'محفظة إلكترونية'), ('delivery_app', 'تطبيق توصيل')], db_index=True, default='cash', max_length=24),
        ),
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة / شبكة'), ('wallet', 'محفظة إلكترونية'), ('delivery_app', 'تطبيق توصيل')], max_length=24)),
                ('terminal_reference', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_payments', to='pos.saletransaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
