# Generated by Django 6.0.2 on 2026-02-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0032_add_kds_order_to_models'),
        ('pos', '0004_kds_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restauranttable',
            name='uniq_branch_table_number',
        ),
        migrations.AlterField(
            model_name='kdsorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kdsorder',
            name='items',
            field=models.JSONField(default=list, help_text='[{name, qty, notes, modifiers}]'),
        ),
        migrations.AlterField(
            model_name='kdsorder',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='أولوية المطبخ (0=عادي، 1=أولوية، 2=عاجل)'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='branch',
            field=models.ForeignKey(help_text='الفرع الذي تنتمي إليه الطاولة', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='org.branch'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='number',
            field=models.CharField(help_text='رقم الطاولة أو اسمها (مثل: T1، VIP-3)', max_length=16),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='pos_x',
            field=models.SmallIntegerField(default=0, help_text='X position in floor plan grid'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='pos_y',
            field=models.SmallIntegerField(default=0, help_text='Y position in floor plan grid'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='section',
            field=models.CharField(blank=True, default='', help_text='اسم القسم (مثل: داخلي، خارجي، VIP)', max_length=64),
        ),
        migrations.AlterField(
            model_name='tablemerge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('branch', 'number')},
        ),
    ]
