# Generated by Django 6.0.2 on 2026-03-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('template_type', models.CharField(choices=[('form', 'Form / نموذج'), ('line_item', 'Line Item / سطر تفصيلي'), ('list', 'List / قائمة')], db_index=True, default='form', max_length=16)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_template', models.ForeignKey(blank=True, help_text='For line_item: the parent form template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_templates', to='customizer.entitytemplate')),
            ],
            options={
                'verbose_name': 'Entity Template',
                'verbose_name_plural': 'Entity Templates',
                'ordering': ['app_label', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(db_index=True, max_length=80)),
                ('label_ar', models.CharField(blank=True, default='', max_length=200)),
                ('label_en', models.CharField(blank=True, default='', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Select'), ('currency', 'Currency'), ('foreign_key', 'Foreign Key')], db_index=True, default='text', max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=True, help_text='True = existing model field (order/visibility only). False = custom field (value in CustomFieldValue).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='customizer.entitytemplate')),
            ],
            options={
                'verbose_name': 'Dynamic Field Definition',
                'verbose_name_plural': 'Dynamic Field Definitions',
                'ordering': ['template', 'order', 'field_key'],
                'unique_together': {('template', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('value_text', models.TextField(blank=True, db_index=True, default='')),
                ('value_number', models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=18, null=True)),
                ('value_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customizer.dynamicfielddefinition')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='customizer__content_fe8a8c_idx'), models.Index(fields=['field_definition', 'value_text'], name='customizer__field_d_257941_idx')],
                'unique_together': {('content_type', 'object_id', 'field_definition')},
            },
        ),
    ]
