# Generated by Django 6.0.2 on 2026-02-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendancerecord_leaverequest_salaryadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='within_geo_fence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='career_history',
            field=models.JSONField(blank=True, default=list, help_text='[{ from_date, to_date, company, position }]'),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='EmployeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deducted_in_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_deductions', to='hr.payrollrun')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
