# Generated by Django 6.0.2
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("org", "0002_add_submission_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(blank=True, default="en", max_length=8),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_type", models.CharField(choices=[("user_profile_changes", "User Profile / Email Changes"), ("account_freeze_activate", "Account Freeze/Activate Actions"), ("excel_sales_uploads", "Excel Sales Uploads (8OZ/Blanca)"), ("shift_closing_updates", "Shift Closing Updates")], max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("user_profile_updated", "User profile/email updated"), ("user_frozen", "User account frozen"), ("user_activated", "User account activated"), ("user_created", "New user added to branch"), ("excel_uploaded", "Excel sales uploaded"), ("shift_closed", "Shift closing submitted")], max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admin_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
