# Generated by Django 6.0.2 on 2026-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_system_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='system_code',
            field=models.CharField(db_index=True, default='OR1001', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='brand',
            name='system_code',
            field=models.CharField(db_index=True, default='OR1002', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='city',
            name='system_code',
            field=models.CharField(db_index=True, default='OR1003', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='all_brands',
            field=models.BooleanField(default=False, help_text='General Manager: access to all brands [Ref: 2026-02-13].'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='brand_ids',
            field=models.JSONField(blank=True, default=list, help_text='Brands Supervisor: list of brand IDs when >1 brand [Ref: 2026-02-13].'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='system_code',
            field=models.CharField(db_index=True, default='OR1004', help_text='ERP hierarchy code', max_length=16),
        ),
    ]
