# Generated by Django 6.0.2 on 2026-02-15 22:24

import django.db.models.deletion
from django.db import migrations, models


def _backfill_city_option_codes(apps, schema_editor):
    City = apps.get_model("org", "City")
    for i, city in enumerate(City.objects.order_by("id"), start=1):
        if not city.option_code:
            city.option_code = f"CITY-{i:02d}"
            city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_branch_system_code_alter_brand_system_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='OR1006', max_length=16)),
                ('option_code', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='option_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique display code e.g. CITY-01', max_length=16),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='org.branchtype'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='OR1005', max_length=16)),
                ('option_code', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='org.city')),
            ],
            options={
                'unique_together': {('city', 'name_en')},
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='org.district'),
        ),
        migrations.RunPython(
            lambda apps, schema: _backfill_city_option_codes(apps, schema),
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='city',
            name='option_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique display code e.g. CITY-01', max_length=16, unique=True),
        ),
    ]
