# Generated by Django 6.0.2 on 2026-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_seed_branch_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='chart_exp_prefix',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Chart of accounts expense prefix (e.g. 051010101). Used for report filtering.', max_length=16),
        ),
        migrations.AddField(
            model_name='brand',
            name='chart_rev_prefix',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Chart of accounts revenue prefix (e.g. 0410101). Used for report filtering.', max_length=16),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(blank=True, default='', help_text='Code-based identifier (e.g. 001, HEMI_HQ). Shown in reports/filters as-is.', max_length=16, unique=True),
        ),
    ]
