# Generated by Django 6.0.2 on 2026-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_populate_brand_chart_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic display name for reports', max_length=120),
        ),
    ]
