# Generated by Django 6.0.2 on 2026-02-17 09:50

from django.db import migrations


def populate_name_ar(apps, schema_editor):
    Brand = apps.get_model("org", "Brand")
    for b in Brand.objects.all():
        if not (b.name_ar or "").strip():
            b.name_ar = b.name or ""
            b.save(update_fields=["name_ar"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0013_add_brand_name_ar"),
    ]

    operations = [
        migrations.RunPython(populate_name_ar, noop),
    ]
