# Generated by Django 6.0.2 on 2026-02-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_populate_brand_name_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('general_manager', 'General Manager'), ('brand_manager', 'Brand Manager'), ('branch_supervisor', 'Branch Supervisor'), ('external_accountant', 'External Accountant')], default='branch_supervisor', max_length=32),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'تسجيل دخول'), ('page_view', 'عرض صفحة'), ('file_upload', 'رفع ملف'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير')], max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('page_path', models.CharField(blank=True, default='', max_length=256)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('target_model', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'سجل الرقابة',
                'ordering': ['-created_at'],
            },
        ),
    ]
