# Generated by Django 6.0.2 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_role_permission_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(choices=[('user_profile_updated', 'User profile/email updated'), ('user_frozen', 'User account frozen'), ('user_activated', 'User account activated'), ('user_created', 'New user added to branch'), ('excel_uploaded', 'Excel sales uploaded'), ('shift_closed', 'Shift closing submitted'), ('chart_account_missing', 'Chart account missing - قيد يستخدم حساباً غير موجود')], max_length=64),
        ),
    ]
