# Generated by Django 6.0.2 on 2026-02-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0019_add_system_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='للتفادي من التكرار، مثلاً stale_transfer_123', max_length=128),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(choices=[('user_profile_updated', 'User profile/email updated'), ('user_frozen', 'User account frozen'), ('user_activated', 'User account activated'), ('user_created', 'New user added to branch'), ('excel_uploaded', 'Excel sales uploaded'), ('shift_closed', 'Shift closing submitted'), ('chart_account_missing', 'Chart account missing - قيد يستخدم حساباً غير موجود'), ('negative_stock', 'رصيد سالب - تنبيه حرج'), ('stale_transfer', 'تحويل عالق أكثر من 24 ساعة')], max_length=64),
        ),
    ]
