# Generated by Django 6.0.2 on 2026-02-23 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_add_system_task_heartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='OR1000', help_text='ERP hierarchy code', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('org_code', models.CharField(blank=True, db_index=True, default='', help_text='كود المؤسسة (مثل ORG001)', max_length=16, unique=True)),
                ('tax_number', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(choices=[('user_profile_updated', 'User profile/email updated'), ('user_frozen', 'User account frozen'), ('user_activated', 'User account activated'), ('user_created', 'New user added to branch'), ('excel_uploaded', 'Excel sales uploaded'), ('shift_closed', 'Shift closing submitted'), ('chart_account_missing', 'Chart account missing - قيد يستخدم حساباً غير موجود'), ('negative_stock', 'رصيد سالب - تنبيه حرج'), ('stale_transfer', 'تحويل عالق أكثر من 24 ساعة'), ('daily_reconciliation_mismatch', 'فجوة في المطابقة اليومية – مبيعات منتجات/يومية/إقفالات')], max_length=64),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='EnterpriseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(db_index=True, default='AU1001', max_length=16)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=16)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('changed_fields', models.JSONField(default=dict, help_text='الحقول المتغيرة مع القيم القديمة/الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise Audit Log',
                'verbose_name_plural': 'سجل التدقيق المؤسسي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='المؤسسة الأم – عزل البيانات حسب الـ Tenant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='org.organization'),
        ),
    ]
