# Generated by Django 6.0.2 on 2026-02-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_moduleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='geo_fence_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='geo_fence_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='geo_fence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='نصف قطر النطاق الجغرافي بالأمتار (مثلاً 100)', null=True),
        ),
    ]
