# Generated by Django 6.0.2 on 2026-02-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_hr_geo_payroll_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_central_kitchen',
            field=models.BooleanField(db_index=True, default=False, help_text='المطبخ المركزي – يستقبل طلبات التحويل من الفروع'),
        ),
    ]
