# Generated by Django 6.0.2 on 2026-02-23 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('org', '0027_add_central_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='Default currency for this brand (e.g. SAR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='currencies.currency'),
        ),
    ]
