# Generated by Django 6.0.2 on 2026-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_add_brand_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(choices=[('user_profile_updated', 'User profile/email updated'), ('user_frozen', 'User account frozen'), ('user_activated', 'User account activated'), ('user_created', 'New user added to branch'), ('excel_uploaded', 'Excel sales uploaded'), ('excel_parse_error', 'Excel parse error'), ('shift_closed', 'Shift closing submitted'), ('chart_account_missing', 'Chart account missing - قيد يستخدم حساباً غير موجود'), ('negative_stock', 'رصيد سالب - تنبيه حرج'), ('stale_transfer', 'تحويل عالق أكثر من 24 ساعة'), ('daily_reconciliation_mismatch', 'فجوة في المطابقة اليومية – مبيعات منتجات/يومية/إقفالات'), ('notification_engine', 'تنبيه من محرك التنبيهات (وردية، مخزون، إلخ)')], max_length=64),
        ),
    ]
