# Generated by Django 6.0.2 on 2026-02-28 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0031_add_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='المستخدم المالك الأول للـ Tenant', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_branches',
            field=models.PositiveSmallIntegerField(default=1, help_text='الحد الأقصى لعدد الفروع حسب الخطة'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='onboarding_complete',
            field=models.BooleanField(default=False, help_text='True بعد إتمام Onboarding Wizard'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='organization',
            field=models.OneToOneField(help_text='المؤسسة الرئيسية (Enterprise) التابعة لهذا الـ Tenant', on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to='org.organization'),
        ),
    ]
