# Generated by Django 6.0.2 on 2026-02-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0015_add_stock_transfer_uuid'),
        ('org', '0026_hr_geo_payroll_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('bronze', 'برونزي'), ('silver', 'فضي'), ('gold', 'ذهبي'), ('platinum', 'بلاتيني')], db_index=True, default='bronze', max_length=16),
        ),
        migrations.CreateModel(
            name='LoyaltyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('offer_type', models.CharField(db_index=True, default='buy_x_get_y', max_length=24)),
                ('buy_x', models.PositiveIntegerField(default=1, help_text='اشترِ كم')),
                ('get_y', models.PositiveIntegerField(default=0, help_text='احصل على كم مجاناً')),
                ('points_per_sar', models.DecimalField(blank=True, decimal_places=2, help_text='نقاط لكل ريال مكرر', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_offers', to='org.brand')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_offers', to='inventory.foodicsproduct')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
