# Generated by Django 6.0.2
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("org", "0003_user_profile_extensions_and_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("brand_slug", models.CharField(blank=True, default="", max_length=64)),
                ("branch_ids", models.JSONField(default=list)),
                ("report_type", models.CharField(blank=True, default="daily_sales", max_length=32)),
                ("date_range_days", models.IntegerField(default=1, help_text="1=today, 7=last 7 days, etc.")),
                ("is_default", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_views", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
