# Generated by Django 6.0.2 on 2026-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredient_system_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstock',
            name='system_code',
            field=models.CharField(db_index=True, default='IU1005', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='foodicsproduct',
            name='system_code',
            field=models.CharField(db_index=True, default='IU1004', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='system_code',
            field=models.CharField(db_index=True, default='IU1003', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='system_code',
            field=models.CharField(db_index=True, default='PR1001', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='system_code',
            field=models.CharField(db_index=True, default='PR1003', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='system_code',
            field=models.CharField(db_index=True, default='IU1006', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='unit',
            name='system_code',
            field=models.CharField(db_index=True, default='IU1002', help_text='ERP hierarchy code (IU1002)', max_length=16),
        ),
    ]
