# Generated by Django 6.0.2 on 2026-02-14 16:37

from django.db import migrations, models


def set_unit_labels(apps, schema_editor):
    Ingredient = apps.get_model("inventory", "Ingredient")
    labels = {
        "RM-001": {"ar": "علبة (2.8 لتر)", "en": "Box (2.8 L)"},
        "RM-002": {"ar": "كيس (1 كجم)", "en": "Bag (1 kg)"},
        "RM-003": {"ar": "كيس (1 كجم)", "en": "Bag (1 kg)"},
        "RM-011": {"ar": "علبة (1.5 كجم)", "en": "Box (1.5 kg)"},
    }
    for serial_code, lbl in labels.items():
        Ingredient.objects.filter(serial_code=serial_code).update(
            workable_unit_label_ar=lbl["ar"], workable_unit_label_en=lbl["en"]
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_branchstock_system_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='workable_unit_label_ar',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='workable_unit_label_en',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(set_unit_labels, noop),
    ]
