# Generated by Django 6.0.2 on 2026-02-14 17:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_workable_unit_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Cost per base unit (SAR)', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='IU1007', max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('theoretical_usage', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Expected usage from Prep List (base units)', max_digits=14)),
                ('actual_usage', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Actual usage recorded (base units)', max_digits=14)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Variance %: ((actual - theoretical) / theoretical) * 100', max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='inventory.ingredient')),
            ],
            options={
                'ordering': ['-date', 'ingredient__name_en'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'date'), name='uniq_waste_log_ingredient_date')],
            },
        ),
    ]
