# Generated by Django 6.0.2 on 2026-02-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_unit_cost_and_waste_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.wastelog',),
        ),
    ]
