# Generated by Django 6.0.2 on 2026-02-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_wasteentry'),
        ('org', '0016_role_permission_config'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wastelog',
            name='uniq_waste_log_ingredient_date',
        ),
        migrations.AddField(
            model_name='wastelog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع – مطلوب لتتبع الهدر حسب الفرع. null للتسجيلات القديمة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='org.branch'),
        ),
        migrations.AddConstraint(
            model_name='wastelog',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('ingredient', 'date'), name='uniq_waste_log_legacy'),
        ),
        migrations.AddConstraint(
            model_name='wastelog',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('ingredient', 'date', 'branch'), name='uniq_waste_log_ingredient_date_branch'),
        ),
    ]
