# Generated by Django 6.0.2 on 2026-02-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_transfer_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='وصفة فرعية: عندما يكون المكوّن نصف مصنع، اربطه بمنتج له وصفة لتفكيك الخصم هرمياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ingredients', to='inventory.foodicsproduct'),
        ),
    ]
