# Generated by Django 6.0.2 on 2026-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_stock_transfer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='package_is_active',
            field=models.BooleanField(default=True, help_text='إذا False: العبوة موقفة ولا تُستخدم في التقارير (عند وجود حركات مخزنية)'),
        ),
    ]
