# Generated by Django 6.0.2 on 2026-02-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_package_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_display_unit',
            field=models.CharField(choices=[('base', 'Base Unit'), ('package', 'Package')], default='base', help_text='الوحدة الافتراضية التي تظهر في جميع التقارير بلا استثناء', max_length=16),
        ),
    ]
