# Generated by Django 6.0.2 on 2026-02-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_default_display_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, default='', max_length=120)),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text='عدد الوحدات الأساسية في هذه العبوة (مثل: 12 قطعة في الكرتون)', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='العبوة الافتراضية التي تظهر في التقارير والمشتريات')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='inventory.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient Package',
                'verbose_name_plural': 'Ingredient Packages',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
