# Generated by Django 6.0.2 on 2026-02-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_ingredient_package_and_active'),
        ('inventory', '0019_migrate_existing_packages_to_model'),
    ]

    operations = [
    ]
