# Generated by Django 6.0.2 on 2026-02-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_merge_20260226_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientpackage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Ingredient Package', 'verbose_name_plural': 'Ingredient Packages'},
        ),
        migrations.AlterUniqueTogether(
            name='ingredientpackage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='active_package',
        ),
        migrations.AddField(
            model_name='ingredientpackage',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='العبوة الافتراضية التي تظهر في التقارير والمشتريات'),
        ),
        migrations.AlterField(
            model_name='ingredientpackage',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, help_text='عدد الوحدات الأساسية في هذه العبوة (مثل: 12 قطعة في الكرتون)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ingredientpackage',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredientpackage',
            name='name_en',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredientpackage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
