# Generated by Django 6.0.2 on 2026-02-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_recipeline_waste_percentage'),
        ('inventory', '0021_alter_ingredientpackage_options_and_more'),
    ]

    operations = [
    ]
