# Generated by Django 6.0.2 on 2026-02-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_merge_20260228_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodicsproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('beverages', 'مشروبات'), ('meals', 'وجبات'), ('desserts', 'حلويات'), ('grocery', 'بقالة'), ('snacks', 'سناكات'), ('other', 'أخرى')], db_index=True, default='other', help_text='فئة المنتج للتحليلات', max_length=24),
        ),
    ]
