# Generated by Django 6.0.2 on 2026-02-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('hourly_sales', 'Hourly Sales'), ('daily_sales', 'Daily Sales'), ('product_sales', 'Product Sales')], max_length=32)),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('report_date_from', models.DateField(blank=True, null=True)),
                ('report_date_to', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org.brand')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('network_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.brand')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rows', to='imports.excelupload')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'date'], name='imports_dai_branch__94c740_idx')],
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('network_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.brand')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rows', to='imports.excelupload')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'date'], name='imports_hou_branch__de3543_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', max_length=128)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.brand')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rows', to='imports.excelupload')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'date'], name='imports_pro_branch__3c7f35_idx'), models.Index(fields=['product_name'], name='imports_pro_product_dbc5e6_idx')],
            },
        ),
    ]
