# Generated by Django 6.0.2 on 2026-02-10 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hourlysale',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
