# Generated by Django 6.0.2 on 2026-02-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_add_payments_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='order_count',
            field=models.PositiveIntegerField(default=0, help_text='عدد الطلبات / Order Count'),
        ),
    ]
