# Generated by Django 6.0.2 on 2026-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_system_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='system_code',
            field=models.CharField(db_index=True, default='SD1001', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='system_code',
            field=models.CharField(db_index=True, default='SU1004', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='hourlysale',
            name='system_code',
            field=models.CharField(db_index=True, default='SD1002', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='system_code',
            field=models.CharField(db_index=True, default='SP1003', help_text='ERP hierarchy code (SP1003)', max_length=16),
        ),
    ]
