# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0007_alter_dailysale_system_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelupload",
            name="progress_pct",
            field=models.PositiveSmallIntegerField(default=0, help_text="0–100 أثناء المعالجة"),
        ),
        migrations.AddField(
            model_name="excelupload",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
