# Generated by Django 6.0.2 on 2026-02-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0032_add_kds_order_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter - 500 SAR/month (1 branch)'), ('pro', 'Pro - 1500 SAR/month (5 branches)'), ('enterprise', 'Enterprise - 4000 SAR/month (unlimited)')], db_index=True, default='trial', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='org.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
            },
        ),
    ]
