# Generated by Django 6.0.2 on 2026-02-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_add_security_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('late_night', 'Late Night')], db_index=True, default='morning', max_length=16),
        ),
        migrations.AddField(
            model_name='shiftclosing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='shiftclosing',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftclosing',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_closings', to=settings.AUTH_USER_MODEL),
        ),
    ]
