# Generated by Django 6.0.2 on 2026-02-23 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_stock_transfer_uuid'),
        ('org', '0025_moduleconfig'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='procurement.supplier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_portal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_level', models.DecimalField(decimal_places=4, help_text='عند الوصول لهذا المستوى', max_digits=14)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, help_text='الكمية المطلوبة', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_reorder_rules', to='org.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_reorder_rules', to='org.brand')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auto_reorder_rules', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='procurement.supplier')),
            ],
            options={
                'unique_together': {('branch', 'ingredient')},
            },
        ),
    ]
