# Generated by Django 6.0.2 on 2026-02-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_supplierportaluser_autoreorderrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreorderrule',
            name='lookback_days',
            field=models.PositiveIntegerField(default=30, help_text='أيام الرجوع لحساب معدل الاستهلاك'),
        ),
        migrations.AddField(
            model_name='autoreorderrule',
            name='use_consumption',
            field=models.BooleanField(default=False, help_text='استخدام معدل الاستهلاك للتنبؤ بدل النقطة الثابتة'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_days',
            field=models.PositiveIntegerField(default=0, help_text='أيام الائتمان (صفر = دفعة مقدمة)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
