# Generated by Django 6.0.2 on 2026-02-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_erp_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='portal_api_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مفتاح API للبوابة – للموردين تسجيل الفواتير آلياً', max_length=64),
        ),
    ]
