# Generated by Django 6.0.2 on 2026-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_add_portal_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, help_text='When the current hashed key was generated.', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of the supplier portal API key. Never store the raw key.', max_length=64),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_key_revoked',
            field=models.BooleanField(default=False, help_text="Set True to immediately invalidate the supplier's portal access."),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='portal_api_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='مفتاح API القديم — نص صريح. استخدم api_key_hash للمفاتيح الجديدة.', max_length=64),
        ),
    ]
