# Generated by Django 6.0.2 on 2026-03-03 21:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_product_category'),
        ('procurement', '0005_add_supplier_hashed_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='subtotal_excl_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_amount_incl_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='subtotal_excl_vat + total_vat_amount', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='إجمالي الفاتورة (معادل total_amount_incl_vat إن وُجد)', max_digits=14),
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_code', models.CharField(db_index=True, default='PR1006', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price_excl_vat', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة الضريبة % (مثل 15)', max_digits=5)),
                ('line_total_excl_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total_incl_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='line_total_excl_vat + line_vat_amount', max_digits=14)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='inventory.ingredient')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.supplierinvoice')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='inventory.unit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
