# Generated by Django 6.0.2 on 2026-02-10 09:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_petty_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='org.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bills_500', models.PositiveIntegerField(default=0)),
                ('bills_200', models.PositiveIntegerField(default=0)),
                ('bills_100', models.PositiveIntegerField(default=0)),
                ('bills_50', models.PositiveIntegerField(default=0)),
                ('bills_20', models.PositiveIntegerField(default=0)),
                ('bills_10', models.PositiveIntegerField(default=0)),
                ('bills_5', models.PositiveIntegerField(default=0)),
                ('bills_1', models.PositiveIntegerField(default=0)),
                ('manual_cash_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: manual cash total override', max_digits=12, null=True)),
                ('mada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('visa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('master_card', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hungerstation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('jahez', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lugmety', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('the_chefz', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('toyou', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expenses_vouchers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('staff_drinks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('system_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('system_network', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('system_delivery', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('system_total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_network', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='shifts.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
