# Generated by Django 6.0.2 on 2026-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_system_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='system_code',
            field=models.CharField(db_index=True, default='SH1001', help_text='ERP hierarchy code', max_length=16),
        ),
        migrations.AlterField(
            model_name='shiftclosing',
            name='system_code',
            field=models.CharField(db_index=True, default='SH1002', help_text='ERP hierarchy code', max_length=16),
        ),
    ]
