# Generated by Django 6.0.2 on 2026-02-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shift_system_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClosingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='shifts/attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shifts.shiftclosing')),
            ],
            options={
                'verbose_name': 'Shift Closing Attachment',
                'verbose_name_plural': 'Shift Closing Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
