# Generated by Django 6.0.2 on 2026-02-10 12:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodicsSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
                ('file', models.FileField(upload_to='accounting/settlements/')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount reportedly deposited to bank', max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='org.branch')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('branch', 'report_date')},
            },
        ),
    ]
