# Generated by Django 6.0.2 on 2026-02-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_add_foodics_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAccountingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_daily_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Accounting Status',
            },
        ),
    ]
