# Generated by Django 6.0.2 on 2026-02-13 00:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_submission_flow'),
        ('org', '0004_saved_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodicsPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('cash', 'Cash / كاش'), ('span', 'Span / سبان'), ('delivery_apps', 'Delivery Apps / تطبيقات التوصيل')], db_index=True, max_length=32)),
                ('raw_method', models.CharField(blank=True, default='', help_text='Original طريقة الدفع value', max_length=128)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodics_payment_records', to='org.branch')),
            ],
            options={
                'ordering': ['-report_date', 'branch'],
                'indexes': [models.Index(fields=['branch', 'report_date', 'category'], name='accounting__branch__ed9b43_idx')],
            },
        ),
    ]
